Repository jekyll/jekyll-feed, pull requests merged in 2020-06, with the labels that each got.

#233 Dont forget about categories
  lib/jekyll-feed/feed.xml
Labels: enhancement, needs-tests

#307 chore(deps): require Ruby >=2.4.0
  appveyor.yml
  jekyll-feed.gemspec
Labels: dependency

#264 Feed by tag
  README.md
  lib/jekyll-feed/feed.xml
  lib/jekyll-feed/generator.rb
  spec/fixtures/_posts/2013-12-12-dec-the-second.md
  spec/fixtures/_posts/2014-03-02-march-the-second.md
  spec/fixtures/_posts/2014-03-04-march-the-fourth.md
  spec/fixtures/_posts/2015-01-18-jekyll-last-modified-at.md
  spec/fixtures/_posts/2015-05-12-pre.html
  spec/fixtures/_posts/2015-05-18-author-detail.md
  spec/fixtures/_posts/2015-08-08-stuck-in-the-middle.html
  spec/jekyll-feed_spec.rb
Labels: feature

#153 add support for categories frontmatter
  lib/jekyll-feed/generator.rb
  spec/fixtures/_posts/2014-03-02-march-the-second.md
  spec/fixtures/_posts/2015-05-12-liquid.md
  spec/jekyll-feed_spec.rb
Labels: enhancement
